name: Build and publish

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build docker images and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Building images and pushing to docker hub
        run: |
          docker buildx build --tag oxmix/hgls-collector:2 \
                              --tag oxmix/hgls-collector:latest \
                              --push --platform linux/amd64,linux/arm64 .
